### ISSUE TITLE
Attach not working

### ISSUE THREAD

**Issue by WhatAboutWaxy** [crashb/jestercap#20]
Is there supposed to be an "Attach" button? Normally when I submit issues to any kind of software it's just me being dumb but since theres like 6 things total in the UI theres no way I'm missing something. Also I wish I knew why my score is 1.9M because I haven't done anything substantial in game.
![image](https://user-images.githubusercontent.com/91380906/213591900-8d1adc75-c68b-4da0-ae88-a26e27765f45.png)

**Comment by crashb** [comment]
Hi there. The score value is wrong because JesterCap is reading the wrong value from Spelunky 2's memory; this bug is occurring because JesterCap had not yet been updated for the current version Spelunky 2 (version 1.28).

@Squidmobile has made the necessary changes to provide compatibility, and I have created a new release that is compatible with this version of Spelunky 2: [link](https://github.com/crashb/jestercap/releases/tag/1.28_01). Please try that release and let me know whether it works for you.

To your other question: there is no "Attach" button. Older versions of JesterCap had one, but now it automatically detects whether the Spelunky 2 process is running on your computer and attaches automatically.

**Comment by WhatAboutWaxy** [comment]
sweet, I downloaded the 1.28 version and it works perfectly. thanks man
